# Generated by Django 4.2.3 on 2023-07-06 22:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("posts", "0002_comment_image_like_delete_postimages_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="like",
            name="post",
        ),
        migrations.RemoveField(
            model_name="like",
            name="user",
        ),
        migrations.AlterField(
            model_name="comment",
            name="post",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="comments",
                to="posts.post",
            ),
        ),
        migrations.AlterField(
            model_name="comment",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="comments",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.RemoveField(
            model_name="post",
            name="images",
        ),
        migrations.DeleteModel(
            name="Image",
        ),
        migrations.DeleteModel(
            name="Like",
        ),
        migrations.AddField(
            model_name="post",
            name="images",
            field=models.ImageField(blank=True, upload_to="posts"),
        ),
    ]
